disabled_rules:
- identifier_name
- trailing_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- Carthage
- JobChat/Utils/Libraries

opt_in_rules:
- empty_count
- empty_string

line_length:
  warning: 150
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

function_parameter_count:
  warning: 4
  error: 6

file_length:
  warning: 1000
  error: 1500
