disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
opt_in_rules: # some rules are only opt-in
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - SOStoreAdmin/Resources/R.generated.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly. Give warning only for force casting

force_try:
  severity: warning # explicitly. Give warning only for force casting
# rules that have both warning and error levels, can set just the warning level
# implicitly
function_body_length:
  warning: 50
  error: 60

line_length: 160

identifier_name:
  excluded: # excluded via string array
    - id
    - URL
reporter: "xcode"
