# Uncomment the next line to define a global platform for your project
use_frameworks!
platform :ios, '9.0'

target 'Structure_IOS' do
  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireObjectMapper', '~> 4.1.0'
end
